spring.application.name=derivaciones




spring.datasource.url=jdbc:postgresql://ep-floral-paper-aq5mxen4-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_shSvTN68yLYB
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8087}
pacientes.service.url=${PACIENTES_URL:http://localhost:8085}